In [3]:
import numpy as np
arr1d = np.array([1, 2, 3, 4, 5])
print("Shape of 1D array:", arr1d.shape)
print("Size of 1D array:", arr1d.size)
print("Dimension of 1D array:", arr1d.ndim)
print("Length of 1D array:", len(arr1d))
arr2d = np.array([[1, 2, 3], [4, 5, 6]])
print("Shape of 2D array:", arr2d.shape)
print("Size of 2D array:", arr2d.size)
print("Dimension of 2D array:", arr2d.ndim)
print("Length of 2D array:", len(arr2d))
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print("Shape of 3D array:", arr3d.shape)
print("Size of 3D array:", arr3d.size)
print("Dimension of 3D array:", arr3d.ndim)
print("Length of 3D array:", len(arr3d))

Shape of 1D array: (5,)
Size of 1D array: 5
Dimension of 1D array: 1
Length of 1D array: 5
Shape of 2D array: (2, 3)
Size of 2D array: 6
Dimension of 2D array: 2
Length of 2D array: 2
Shape of 3D array: (2, 2, 3)
Size of 3D array: 12
Dimension of 3D array: 3
Length of 3D array: 2


In [20]:


# arrange
print(np.arange(10))

# random.randint
print(np.random.randint(0, 10))

# random.rand
print(np.random.rand(3))

# linspace
print(np.linspace(0, 10, 5))

# ones
print(np.ones((3, 4)))


# zeros
print(np.zeros((3, 4)))



# diag
print(np.diag([1, 2, 3]))



# sum
print(np.sum([1, 2, 3]))

# min
print(np.min([1, 2, 3]))

# max
print(np.max([1, 2, 3]))

# mean
print(np.mean([1, 2, 3]))

[0 1 2 3 4 5 6 7 8 9]
4
[0.47590365 0.17819245 0.98885285]
[ 0.   2.5  5.   7.5 10. ]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1 0 0]
 [0 2 0]
 [0 0 3]]
6
1
3
2.0


In [21]:

num_students = 45
student_marks = np.random.randint(0, 101, size=num_students)

passed_students = np.sum(student_marks >= 30)

failed_students = student_marks[student_marks < 30]

print("Number of students passed:", passed_students)
print("Failed students' marks:", failed_students)


Number of students passed: 29
Failed students' marks: [24 21 22  3  5  1 13 14  1 27  0 12 29 26 29 22]


In [22]:

rows = 10
cols = 10

random_array = np.random.randint(1, 51, size=(rows, cols))

print(random_array)


[[37 38 42 11 44 49 37 13 12 12]
 [ 9 44  9 22 36  5 50 22  3 38]
 [31  1 50 46 22 26 15  1  1 17]
 [23 49  8 12 38 48 46 28 14 34]
 [46 24 16 21 34 26 31  8 32  6]
 [12 35 32 18  1 47 19 36 46 39]
 [49 39 10 11 14 27 42 20 41 21]
 [46 48 14 32 38 28 36 50 26 14]
 [46 28 28 30 35  2 32  2 15 42]
 [29 17 10 37 29 20 21  1 17 32]]


In [23]:


odd_numbers = np.arange(-29, 11, 2)

print(odd_numbers)


[-29 -27 -25 -23 -21 -19 -17 -15 -13 -11  -9  -7  -5  -3  -1   1   3   5
   7   9]


In [24]:


shape = (2, 3, 4)

random_3d_array = np.random.randint(10, 41, size=shape)

print(random_3d_array)


[[[30 14 14 24]
  [13 23 37 13]
  [35 33 28 13]]

 [[26 17 26 16]
  [16 33 31 24]
  [35 35 35 10]]]


In [25]:

ones_array = np.ones((3, 2, 3))

print(ones_array)


[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


In [26]:

zeros_array = np.zeros((3, 2, 3))

print(zeros_array)


[[[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]]
